version: 2.1

description: |
  Collection of useful Git-related tools for all VCS providers

###########
#EXECUTORS#
###########
# Executors are used to define environments in which jobs are ran

executors:
  default:
    description: Basic container for running CircleCI commands.
    docker:
      - image: circleci/circleci-cli

##########
#COMMANDS#
##########
# Commands are executed within jobs to perform tasks

commands:
  #1
  prcomment:
    description: "If the current commit is a part of a pull request, the commit message will be added to the PR as a comment. Only available for GitHub"
    parameters:
      token:
        description: "GitHub API token for accessing issue comments endpoint. This should be set to $VCS_TOKEN"
        type: string
        default: ${VCS_TOKEN}
    steps:
      - run:
          name: "Commenting Pull Request"
          command: |
            if [ -z $CIRCLE_PULL_REQUEST ]
            then
              echo "The current build is not a Pull Request. If you intend to open an pull request after this commit, all following commits will be commented"
            else
              echo $CIRCLE_PROJECT_USERNAME
              echo $CIRCLE_PROJECT_REPONAME
              echo $CIRCLE_PR_NUMBER
              # curl -H "Authorization: token ${VCS_TOKEN}" -X POST \
              # -d "{\"body\": \"Hello world\"}" \
              # "https://api.github.com/repos/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}/issues/${CIRCLE_PR_NUMBER}"
            fi

######
#JOBS#
######
# Jobs initiate a set of commands

jobs:
  prcomment:
    description: "If the current commit is a part of a pull request, the commit message will be added to the PR as a comment. Only available for GitHub"
    executor: default
    steps:
      - prcomment