version: 2.1

description: |
  Collection of useful Git-related tools for all VCS providers

###########
#EXECUTORS#
###########
# Executors are used to define environments in which jobs are ran

executors:
  default:
    description: Basic container for running CircleCI commands.
    docker:
      - image: circleci/circleci-cli

##########
#COMMANDS#
##########
# Commands are executed within jobs to perform tasks

commands:
  #1
  git-tools-setup:
    description: "Configure settings for multi-VCS support."
    steps:
      - run:
          name: "Git-Tools Setup"
          command: |
            # Setup any needed ENV VARS for all other commands here.
            #
            # Set VCS_TYPE
            echo "Setting VCS_TYPE"
            VCS_TYPE=$(echo $CIRCLE_PULL_REQUEST | awk -F[/:] '{print $4}' | awk -F[.] '{print $1}')
            echo "VCS_TYPE is set to " $VCS_TYPE
            echo "export VCS_TYPE=${VCS_TYPE}" >> ~/.bashrc
            cat ~/.bashrc
  #2
  prcomment:
    description: "If the current commit is a part of a pull request, the commit message will be added to the PR as a comment. Only available for GitHub"
    parameters:
      token:
        description: "GitHub API token for accessing issue comments endpoint. This should be set to $VCS_TOKEN"
        type: string
        default: ${VCS_TOKEN}
    steps:
      - git-tools-setup
      - run:
          name: "Commenting Pull Request"
          command: |
            source ~/.bashrc
            cat ~/.bashrc
            if [ -z $CIRCLE_PULL_REQUEST ]
            then
              # The current commit is not a PR
              echo "The current build is not a Pull Request. If you intend to open an pull request after this commit, all following commits will be commented"
            else
              # Comment on pull request
              echo "VCS TYPE: " $VCS_TYPE
              echo $CIRCLE_PULL_REQUEST
              # curl -H "Authorization: token ${VCS_TOKEN}" -X POST \
              # -d "{\"body\": \"Hello world\"}" \
              # "https://api.github.com/repos/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}/issues/${CIRCLE_PR_NUMBER}"
            fi

######
#JOBS#
######
# Jobs initiate a set of commands

jobs:
  prcomment:
    description: "If the current commit is a part of a pull request, the commit message will be added to the PR as a comment. Only available for GitHub"
    executor: default
    steps:
      - prcomment